// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuwP8W-1XTQW9EB1jZuWoDyAfvlwk45TY',
    appId: '1:207911979720:web:e3e5e50a46996a2013f3fd',
    messagingSenderId: '207911979720',
    projectId: 'vehicle-33e6f',
    authDomain: 'vehicle-33e6f.firebaseapp.com',
    storageBucket: 'vehicle-33e6f.appspot.com',
    measurementId: 'G-W54PKZSSDB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKgZdy3GHLQDhIWlLxOmQvY6YDgxdaneo',
    appId: '1:207911979720:android:6b8126e2fcd65d9b13f3fd',
    messagingSenderId: '207911979720',
    projectId: 'vehicle-33e6f',
    storageBucket: 'vehicle-33e6f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgYCpLXbltx0K4gzxLu8uLxKZXy-Kk-hc',
    appId: '1:207911979720:ios:f2b74c5c6b34651713f3fd',
    messagingSenderId: '207911979720',
    projectId: 'vehicle-33e6f',
    storageBucket: 'vehicle-33e6f.appspot.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAgYCpLXbltx0K4gzxLu8uLxKZXy-Kk-hc',
    appId: '1:207911979720:ios:69235ec12385e30d13f3fd',
    messagingSenderId: '207911979720',
    projectId: 'vehicle-33e6f',
    storageBucket: 'vehicle-33e6f.appspot.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
